### ISSUE TITLE
Any chance you can add Midnight Commander?

### ISSUE THREAD

**Issue by saghul** [dmacias72/unRAID-NerdPack#1]
Hey Derek, awesome work, I really like the plugin! ❤️  I was wondering if you could add Midnight Commander, which would make my life easier, for moving stuff around while on a tmux session :-)

Cheers!

**Comment by dmacias72** [comment]
Your welcome. I'm glad you find it useful. Midnight Commander has always been part of unRAID since I've been using it. Just type mc from the console.

**Comment by saghul** [comment]
Sigh, I'm an idiot, I hadn't even tried it! Thanks!

**Comment by dmacias72** [comment]
Your welcome. Don't worry your not the only one to miss that mc was included.
