### ISSUE TITLE
Request: Add Git-LFS Package

### ISSUE THREAD

**Issue by drfuzzyness** [dmacias72/unRAID-NerdPack#16]
It's super helpful for managing repos of binary files!

General information about Git-LFS: [https://git-lfs.github.com/](https://git-lfs.github.com/)

It looks like there is a Slackware Build at [https://slackbuilds.org/repository/14.2/development/git-lfs/](https://slackbuilds.org/repository/14.2/development/git-lfs/).

I've tested the Slackware Build manually and it appears to work as expected, although as a user I need to run `git lfs install` to install the client.

**Comment by dmacias72** [comment]
I added git-lfs
