### ISSUE TITLE
[Package Request] unar

### ISSUE THREAD

**Issue by antonchen** [dmacias72/unRAID-NerdPack#18]
Can you add unar ?
Package:  http://download.salixos.org/x86_64/14.2/salix/ap/unar-1.9.1-x86_64-1gv.txz

Thanks!

**Comment by dmacias72** [comment]
Unrar is already there

**Comment by antonchen** [comment]
Not unrar is unar, unar can decompress almost all compressed files.

**Comment by dmacias72** [comment]
Ah OK. Added.

**Comment by antonchen** [comment]
I tested that unar needs dependencies in unraid 6.7.2:
```
gnustep-base
wavpack
icu4c
gcc-objc
binutils
```

ps: NerdPack automatically install dependencies?

**Comment by dmacias72** [comment]
There's no package manager. I would have to add all those packages. This is outside the scope of this plugin. This plugin is for one or two package applications.
