### ISSUE TITLE
docker-compose for unraid 6.8

### ISSUE THREAD

**Issue by loibi93** [dmacias72/unRAID-NerdPack#24]
Hi,

I have seen that docker-compose is in the 6.7 packages folder but not available for 6.8, any reason for that? Could you add it please for 6.8? :)

regards

**Comment by dmacias72** [comment]
It's not included anymore because I was asked to update it and it requires too many dependencies. However it can be installed with pip just like most python apps that don't need to be compiled. You need python3, setuptools, pip and libffi. Then run pip3 install docker-compose.

**Comment by loibi93** [comment]
Perfect, did work, thank you! :)
