### ISSUE TITLE
Perl Update 5.30.2 -> 5.32.0

### ISSUE THREAD

**Issue by kubedzero** [dmacias72/unRAID-NerdPack#30]
https://packages.slackware.com/?r=slackware64-current&p=perl-5.32.0-x86_64-1.txz
https://slackware.pkgs.org/current/slackware-x86_64/perl-5.32.0-x86_64-1.txz.html

The latest version of Perl for Slackware seems to be 5.32.0, possibly released round June 22, 2020. I think the version of Perl being used in Nerd Pack right now is 5.30.2, according to what my dashboard shows after a "Check for Updates" execution, https://github.com/dmacias72/unRAID-NerdPack/blob/master/packages/6.8/perl-5.30.2-x86_64-1.txz, and https://github.com/dmacias72/unRAID-NerdPack/blob/master/packages/6.9/perl-5.30.2-x86_64-1.txz

Is there any chance of updating this to the newest version?

Thanks, and let me know if more information is needed!

**Comment by dmacias72** [comment]
Updated
