### ISSUE TITLE
Borgbackup 1.1.13 -> 1.1.14

### ISSUE THREAD

**Issue by kubedzero** [dmacias72/unRAID-NerdPack#32]
https://github.com/borgbackup/borg/releases/tag/1.1.14

It appears that Borg released an update bugfix. 

Nerd Pack currently has 1.1.13.

I don't think any of the precompiled copies from the Borg Github Repo will work with Unraid, and the only Slackware repo I found it listed  within https://slackbuilds.org/repository/14.2/system/borgbackup/ only has 1.1.13

Curious what the approach was in the past for updating BorgBackup and if there's anything I can do  to help.

Thanks!

**Comment by dmacias72** [comment]
I updated it to 1.1.14. I have an Unraid VM that I load all the packages from DevPack then install a few more borg specific packages and run a slackbuild script and compile it and package it up.
