### ISSUE TITLE
llfuse 1.3.6 incompatible with Python 3.9

### ISSUE THREAD

**Issue by kubedzero** [dmacias72/unRAID-NerdPack#34]
Kind of related to https://github.com/dmacias72/unRAID-NerdPack/issues/33 as I found this issue when trying to run a borg mount on an archive, which utilizes `llfuse`. `borg mount .::20201107 /tmp/tmpborg/` 

In looking around, I found Borg notes posted on 2020-10-07 https://borgbackup.readthedocs.io/en/stable/changes.html?highlight=llfuse saying "llfuse dependency: choose least broken 1.3.6/1.3.7. 1.3.6 is broken on python 3.9, 1.3.7 is broken on FreeBSD."

Since that time, the (deprecated, I know we're eventually moving to pyfuse3) python-llfuse library has been updated from 1.3.7 to 1.3.8. The changelog in 1.3.7 notes "Rebuild with Cython 0.29.21 for Python 3.9 compatibility" and the 1.3.8 release has a few more tweaks https://github.com/python-llfuse/python-llfuse/releases

The current version of llfuse in Nerd Pack is 1.3.6: https://github.com/dmacias72/unRAID-NerdPack/blob/master/packages/6.8/llfuse-1.3.6-x86_64-1_SBo.txz

Would it be possible to update this to 1.3.7 or 1.3.8 so it's functional again with Python 3.9?

Thanks!

**Comment by kubedzero** [comment]
I've been messing around trying to build it myself, but keep running into issues running `setup.py` where it seems to be missing `src/llfuse.c`. If you figure out how to build it, I'll be very interested to find out!

**Comment by kubedzero** [comment]
[llfuse build files.zip](https://github.com/dmacias72/unRAID-NerdPack/files/5507333/llfuse.build.files.zip)

```
root@slack:~# diff oldfuse/oldllfuse.SlackBuild llfuseBuild/llfuse.SlackBuild
29c29
< VERSION=${VERSION:-1.1}
---
> VERSION=${VERSION:-1.3.8}
60c60
< set -e
---
> set -ex
66c66
< tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
---
> tar xvf $CWD/$PRGNAM-$VERSION.tar
74a75
> python setup.py build_cython
78a80
>   python3 setup.py build_cython
86c88
< mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/html
---
> # mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION/html
88,89c90,91
< cp -a doc/html/*.html doc/html/searchindex.js doc/html/_static \
<       $PKG/usr/doc/$PRGNAM-$VERSION/html
---
> # cp -a doc/html/*.html doc/html/searchindex.js doc/html/_static \
> #       $PKG/usr/doc/$PRGNAM-$VERSION/html

```
I set up Slackware-current (15.0) based on a Princeton ISO http://mirror.math.princeton.edu/pub/slackware/slackware-iso/slackware-current-iso/ and then updated all the packages.

I then took the latest release of llfuse, 1.3.8, downloaded it and re-tarred it using a single layer directory and the `llfuse-1.3.8` folder name instead of the Github style folder name.

I then got the SlackBuild script from https://slackbuilds.org/repository/14.2/python/llfuse/ but it was for version 1.1 and a bit outdated. I updated the version number, and as I saw in the dev's build notes https://github.com/python-llfuse/python-llfuse/blob/master/developer-notes/release-process.md I added the line `python setup.py build_cython` to actually compile the llfuse.c file. Before that, I kept getting GCC failures with 

`gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-pro -o build/temp.linux-x86_64-2.7/src/llfuse.o -D_FILE_OFFSET_BITS=64 -I/usr/include/-Wsign-compare -DLLFUSE_VERSION="1.3.7" -Wno-unused-function -Wno-implicit-fallthroerror=unreachable-code -Werror=conversion -Werror=sign-compare -fno-strict-aliasing`
`gcc: error: src/llfuse.c: No such file or directory`

Also in the SlackBuild script (in addition to the version number bump, `set -ex` to see each command printed out before running for debugging help, changing the .tar.bz2 to .tar to match the file I made, and adding the `build_cython` setup.py build targets) I had to comment out the copying over of documentation HTML, as I didn't see any generated when running through the build Python file.

Altogether, I was able to get the script to run until the end and build the Slackware package file! You're welcome to take it as-is or re-build it yourself using the supplied info and files in the ZIP above. 

I was able to load it in manually to Unraid (`Package llfuse-1.3.6-x86_64-1_SBo upgraded with new package ./llfuse-1.3.8-x86_64-1_SBo.tgz.`) and confirmed the Borg mount command I mentioned earlier worked without issue.

**Comment by dmacias72** [comment]
This is one of the packages I compiled myself and probably used the same slackbuild. I should create a folder in this repo with all the slackbuild and info for the packages I compile. I use my DevPack plugin and install all the packages. Then sometimes like for this and borg a have a couple more packages I install manually. The only other thing I change in the script is the extension of the slack pkg from tgz to txz. So if you feel like recompiling it to a txz package and do a pull request. I'll add it. Otherwise I can compile it when I get a chance.

**Comment by kubedzero** [comment]
Sounds good, I'll see about making that change this weekend. Do you want to drop in an empty SlackBuild folder so I can toss in the script as part of the PR as well, or do you have any particular location you want it?

**Comment by dmacias72** [comment]
I added a SlackBuild folder under source. The llfuse package should go under the 6.8 and 6.9 folders in packages. And remove the 1.36 version.

**Comment by kubedzero** [comment]
Merged, this issue can be closed. Thanks!
