### ISSUE TITLE
tmux fails with "open terminal failed: missing or unsuitable terminal: xterm-256color"

### ISSUE THREAD

**Issue by nfriedly** [dmacias72/unRAID-NerdPack#4]
Hey, thanks for creating this, it has just about everything I could want!

However, `tmux` doesn't seem to work out-of-the box (on unraid 6.6.5):

```
root@Unraid:~# tmux
open terminal failed: missing or unsuitable terminal: xterm-256color
```

I tried rebooting, but that didn't make a difference.

After some digging around, I found that `TERM=xterm tmux` works, so it's not completely unusable, just confusing.

It'd be nice if this plugin either made that the default or else installed `xterm-256color` with tmux.

**Comment by nfriedly** [comment]
Also, backspace doesn't seem to work - it just inserts a space (?)

This is going from Terminal.app on my mac, over ssh to my unraid server, then starting tmux with TERM=xterm.

**Comment by dmacias72** [comment]
This is a result of unRAID stripping out all the terminfo from their ncurses package. Similar problems would happen with screen. Backspace wouldn't work. I added /usr/share/terminfo/s/screen to the screen package. I could add xterm-256color to tmux but it might be more useful to create a ncurses-terminfo package that installs terminal info that could be used by other packages

**Comment by dmacias72** [comment]
Actually looking at /usr/share/terminfo/x xterm, xterm-256color and xterm-color are already installed. Unless something else installed them.

**Comment by nfriedly** [comment]
Well, that's curious. It's there for me now too. `tmux` now works without specifying the terminal app, and backspace works. I'm on a windows machine using git-bash now, but I don't think that would make the difference. Maybe running `screen` once caused it to get set up right?
