### ISSUE TITLE
Unraid version detection fails when minor version > 9

### ISSUE THREAD

**Issue by doron1** [dmacias72/unRAID-NerdPack#52]
For Unraid versions with minor version >9 (case in point, 6.10.x), the plugin falls back to a single digit minor version (in the example, 6.1).  This creates all sorts of issues.
Culprit appears to be this line, in NerdPack.plg:
`VER=${version:0:3}`
which obviously picks up only the first digit of the minor version, and similarly, in NerdPackHelpers.php:
`$os_version = substr(parse_ini_file('/etc/unraid-version')['version'],0,3);`

**Comment by tjb-altf4** [comment]
This will fix the php issue
`$os_version = strtok(parse_ini_file('/etc/unraid-version')['version'], '.') . '.' . strtok('.');`

**Comment by doron1** [comment]
Sure, and for the bash issue (plg) it could be:
`VER=$(expr "$version" : "\([0-9]*\.[0-9]*\)")`
