### ISSUE TITLE
Feature Request: ad bluez package

### ISSUE THREAD

**Issue by JoschaMiddendorf** [dmacias72/unRAID-NerdPack#6]
Feature request:

As the new UnRaid 6.7.0 will support bluetooth devices it would be nice to have bluez package installable to be able to use hcitool for debugging purpouses. Could you add that to the NerdPack?

**Comment by dmacias72** [comment]
I added it. Ran a couple things. Seemed to work. It may require a bunch of audio packages if you want to use Bluetooth audio, which is outside the scope of this plugin.

**Comment by JoschaMiddendorf** [comment]
Great. Im just using it to discover the presence of specific bluetooth devices in a home automation environment. Presence detection of Smartphones. Thank you for the very fast response.
