### ISSUE TITLE
request to add davfs2 thanks

### ISSUE THREAD

**Issue by lalasou** [dmacias72/unRAID-NerdPack#61]
Thank you so much, I love this plugin!
Hope to be able to mount webdav
I found information here, but I want to add it to your plugin
https://slackbuilds.org/repository/14.2/system/davfs2/
http://savannah.nongnu.org/projects/davfs2

**Comment by dstephens1980** [comment]
I second this request.  Would make creating offsite backups of shares between multiple unRAID systems using nextcloud/owncloud a lot easier.

**Comment by 2302Dave** [comment]
What happened to this request? Did you find any solution?

**Comment by lalasou** [comment]
Maybe the author was too busy, and finally I used rclone to solve the problem.
