### ISSUE TITLE
 incompatible with your version of Unraid 6.11.0

### ISSUE THREAD

**Issue by vMeph** [dmacias72/unRAID-NerdPack#70]
Plug-in Fix Common Problems is detecting the following problem

`The author (or moderators of Community Applications) of the plugin template (https://raw.githubusercontent.com/dmacias72/unRAID-NerdPack/master/plugin/NerdPack.plg) has specified that this plugin is incompatible with your version of Unraid (6.11.0). You should uninstall the plugin here: Maximum OS Version: 6.10.3 `

**Comment by thecode** [comment]
This is already reported at https://github.com/dmacias72/unRAID-NerdPack/issues/69
