### ISSUE TITLE
6.11.5 Not showing all items?

### ISSUE THREAD

**Issue by mrforsythexeter** [dmacias72/unRAID-NerdPack#71]
Looking at the repo, there is around 125 packages for 6.11. However on my setup (where I had to remove a version as it was reported as not compatible), its showing 46.

I can't work out how you say which ones are compatible, am I meant to be able to see all of the packages, what should I check next?

**Comment by thecode** [comment]
This repo is not active anymore, you need to install NerdTools (not NerdPack) packages will be a little bit different

**Comment by mrforsythexeter** [comment]
Thank you, that makes sense.
